version: "3.8"
services:
  app:
    build: .
    container_name: lab-bd-app
    depends_on:
      - postgres
      - mysql
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=labdb
      - DB_USER=admin
      - DB_PASS=admin
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: npm run dev

  postgres:
    image: postgres:15
    container_name: lab-bd-postgres
    restart: always
    environment:
      POSTGRES_DB: labdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8
    container_name: lab-bd-mysql
    restart: always
    environment:
      MYSQL_DATABASE: labdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  postgres_data:
  mysql_data:
